entrenadores_index:
    path:     /
    defaults: { _controller: "AUCBundle:entrenadores:index" }
    methods:  GET

entrenadores_show:
    path:     /{id}/show
    defaults: { _controller: "AUCBundle:entrenadores:show" }
    methods:  GET

entrenadores_new:
    path:     /new
    defaults: { _controller: "AUCBundle:entrenadores:new" }
    methods:  [GET, POST]

entrenadores_edit:
    path:     /{id}/edit
    defaults: { _controller: "AUCBundle:entrenadores:edit" }
    methods:  [GET, POST]

entrenadores_delete:
    path:     /{id}/delete
    defaults: { _controller: "AUCBundle:entrenadores:delete" }
    methods:  [GET, POST]