jugadores_index:
    path:     /
    defaults: { _controller: "AUCBundle:jugadores:index" }
    methods:  GET

jugadores_show:
    path:     /{id}/show
    defaults: { _controller: "AUCBundle:jugadores:show" }
    methods:  GET

jugadores_new:
    path:     /new
    defaults: { _controller: "AUCBundle:jugadores:new" }
    methods:  [GET, POST]

jugadores_edit:
    path:     /{id}/edit
    defaults: { _controller: "AUCBundle:jugadores:edit" }
    methods:  [GET, POST]

jugadores_delete:
    path:     /{id}/delete
    defaults: { _controller: "AUCBundle:jugadores:delete" }
    methods:  [GET, POST, DELETE]